// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is one release.
 */
export interface Entry {
    /**
     * without the leading "v"
     */
    "version": string;

    /**
     * YYYY-MM-DD
     */
    "date": string;
    "items": string[] | null;
}
