// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChangelogService tells the frontend what changed since the version the
 * user ran last, for the "what's new" dialog after an update.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as changelog$0 from "./internal/changelog/models.js";

/**
 * ReleaseURL is the GitHub page of the running version's release.
 */
export function ReleaseURL(): $CancellablePromise<string> {
    return $Call.ByID(1857577825);
}

/**
 * Seen records that the user has seen the notes for the running version.
 */
export function Seen(): $CancellablePromise<void> {
    return $Call.ByID(3558474032);
}

/**
 * WhatsNew returns the releases since the version that last ran (newest
 * first), or nothing on a fresh install, a dev build, or no version change.
 */
export function WhatsNew(): $CancellablePromise<changelog$0.Entry[] | null> {
    return $Call.ByID(85137496);
}
