// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService manages saved connections, open pools and schema metadata.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbx$0 from "./internal/dbx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Columns lists the columns of schema.table.
 */
export function Columns(id: string, schema: string, table: string): $CancellablePromise<dbx$0.ColumnInfo[] | null> {
    return $Call.ByID(3872334928, id, schema, table);
}

/**
 * CompleteTables returns up to 100 table names in schema starting with prefix.
 */
export function CompleteTables(id: string, schema: string, prefix: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1333347211, id, schema, prefix);
}

/**
 * Completion prepares autocompletion for connection id according to its
 * Autocomplete setting. In automatic mode schemas with up to
 * dbx.PreloadTableLimit tables are loaded up front; larger ones are looked up
 * as the user types.
 */
export function Completion(id: string): $CancellablePromise<$models.CompletionSetup> {
    return $Call.ByID(3795535235, id);
}

/**
 * Connect opens the saved connection id. It fails with errPasswordRequired
 * when the password has to be asked for (see ProvidePassword).
 */
export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3034779341, id);
}

/**
 * Connected returns the ids of open connections.
 */
export function Connected(): $CancellablePromise<string[] | null> {
    return $Call.ByID(392987156);
}

/**
 * DefaultSchema returns the schema unqualified names resolve to.
 */
export function DefaultSchema(id: string): $CancellablePromise<string> {
    return $Call.ByID(2222070805, id);
}

/**
 * Delete removes a saved connection and its password, and closes it if open.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1192434110, id);
}

/**
 * Disconnect closes the connection id and all tab sessions using it.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(2162754255, id);
}

/**
 * ForgetSessionPassword drops a password given with ProvidePassword that
 * turned out to be wrong, so the next connect asks again.
 */
export function ForgetSessionPassword(id: string): $CancellablePromise<void> {
    return $Call.ByID(2405945301, id);
}

/**
 * Import saves conns as new connections. Nothing is saved unless all of them
 * are valid.
 */
export function Import(conns: store$0.Connection[] | null): $CancellablePromise<number> {
    return $Call.ByID(4115736032, conns);
}

/**
 * List returns all saved connections, without passwords.
 */
export function List(): $CancellablePromise<store$0.Connection[] | null> {
    return $Call.ByID(4115594309);
}

/**
 * PasswordStore reports whether the OS password store can be used.
 */
export function PasswordStore(): $CancellablePromise<$models.PasswordStoreInfo> {
    return $Call.ByID(909666965);
}

/**
 * PickDBeaverFolder shows a folder dialog and returns the chosen directory
 * ("" if cancelled).
 */
export function PickDBeaverFolder(): $CancellablePromise<string> {
    return $Call.ByID(2553633517);
}

/**
 * PickSQLiteFile shows a file dialog and returns the chosen path ("" if cancelled).
 */
export function PickSQLiteFile(): $CancellablePromise<string> {
    return $Call.ByID(4215123398);
}

/**
 * ProvidePassword sets the password of connection id after it was asked for
 * on connect. With remember it is saved in the password store; otherwise, or
 * without a password store, it is kept until dbird quits.
 */
export function ProvidePassword(id: string, password: string, remember: boolean): $CancellablePromise<void> {
    return $Call.ByID(4120939103, id, password, remember);
}

/**
 * Save creates or updates a connection. Its password goes to the OS password
 * store (see passwords). An open pool for it is closed so the new settings
 * take effect on the next connect.
 */
export function Save(c: store$0.Connection): $CancellablePromise<store$0.Connection> {
    return $Call.ByID(3893059340, c);
}

/**
 * ScanDBeaver reads the connections of the DBeaver workspace in dir, or of
 * the first one found on this machine when dir is empty. Finding none is not
 * an error: Dir is then empty.
 */
export function ScanDBeaver(dir: string): $CancellablePromise<$models.DBeaverScan> {
    return $Call.ByID(891624637, dir);
}

/**
 * Schemas lists schemas (databases for MySQL) of connection id.
 */
export function Schemas(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1017771595, id);
}

/**
 * TableColumns returns the column names of schema.table, for autocompletion.
 */
export function TableColumns(id: string, schema: string, table: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1134520702, id, schema, table);
}

/**
 * Tables lists tables and views in schema.
 */
export function Tables(id: string, schema: string): $CancellablePromise<dbx$0.TableInfo[] | null> {
    return $Call.ByID(4217470720, id, schema);
}

/**
 * TablesPage lists up to limit (max 1000) tables in schema whose name
 * contains filter, starting after the name after. The first page (after == "")
 * also reports the total, so the sidebar can offer to load more.
 */
export function TablesPage(id: string, schema: string, filter: string, after: string, limit: number): $CancellablePromise<$models.TablePage> {
    return $Call.ByID(3164927595, id, schema, filter, after, limit);
}

/**
 * Test tries to connect with c and returns the server version. Without a
 * typed password it uses the saved one of c (or of the connection c is a
 * duplicate of).
 */
export function Test(c: store$0.Connection): $CancellablePromise<string> {
    return $Call.ByID(960763793, c);
}
