// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService manages saved connections, open pools and schema metadata.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbx$0 from "./internal/dbx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Columns lists the columns of schema.table.
 */
export function Columns(id: string, schema: string, table: string): $CancellablePromise<dbx$0.ColumnInfo[] | null> {
    return $Call.ByID(3872334928, id, schema, table);
}

/**
 * CompleteTables returns up to 100 table names in schema starting with prefix.
 */
export function CompleteTables(id: string, schema: string, prefix: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1333347211, id, schema, prefix);
}

/**
 * Completion prepares autocompletion for connection id according to its
 * Autocomplete setting. In automatic mode schemas with up to
 * dbx.PreloadTableLimit tables are loaded up front; larger ones are looked up
 * as the user types.
 */
export function Completion(id: string): $CancellablePromise<$models.CompletionSetup> {
    return $Call.ByID(3795535235, id);
}

/**
 * Connect opens the saved connection id.
 */
export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3034779341, id);
}

/**
 * Connected returns the ids of open connections.
 */
export function Connected(): $CancellablePromise<string[] | null> {
    return $Call.ByID(392987156);
}

/**
 * DefaultSchema returns the schema unqualified names resolve to.
 */
export function DefaultSchema(id: string): $CancellablePromise<string> {
    return $Call.ByID(2222070805, id);
}

/**
 * Delete removes a saved connection and closes it if open.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1192434110, id);
}

/**
 * Disconnect closes the connection id and all tab sessions using it.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(2162754255, id);
}

/**
 * List returns all saved connections.
 */
export function List(): $CancellablePromise<store$0.Connection[] | null> {
    return $Call.ByID(4115594309);
}

/**
 * PickSQLiteFile shows a file dialog and returns the chosen path ("" if cancelled).
 */
export function PickSQLiteFile(): $CancellablePromise<string> {
    return $Call.ByID(4215123398);
}

/**
 * Save creates or updates a connection. An open pool for it is closed so the
 * new settings take effect on the next connect.
 */
export function Save(c: store$0.Connection): $CancellablePromise<store$0.Connection> {
    return $Call.ByID(3893059340, c);
}

/**
 * Schemas lists schemas (databases for MySQL) of connection id.
 */
export function Schemas(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1017771595, id);
}

/**
 * TableColumns returns the column names of schema.table, for autocompletion.
 */
export function TableColumns(id: string, schema: string, table: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1134520702, id, schema, table);
}

/**
 * Tables lists tables and views in schema.
 */
export function Tables(id: string, schema: string): $CancellablePromise<dbx$0.TableInfo[] | null> {
    return $Call.ByID(4217470720, id, schema);
}

/**
 * Test tries to connect with c and returns the server version.
 */
export function Test(c: store$0.Connection): $CancellablePromise<string> {
    return $Call.ByID(960763793, c);
}
