// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService reads and writes SQL scripts and exports.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * OpenScript asks for a .sql file and returns its contents. A zero value
 * means the dialog was cancelled.
 */
export function OpenScript(): $CancellablePromise<$models.OpenedFile> {
    return $Call.ByID(1099734320);
}

/**
 * SaveAs asks where to save content and writes it. kind selects the file
 * filter ("sql", "csv" or "tsv"). Returns "" if the dialog was cancelled.
 */
export function SaveAs(suggestedName: string, content: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(4000858594, suggestedName, content, kind);
}

/**
 * SaveScript overwrites an existing SQL script previously opened or saved.
 */
export function SaveScript(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1685239685, path, content);
}
