// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService reads and writes SQL scripts and exports, and watches open
 * scripts so edits made in another editor show up in dbird.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * OpenExternally opens a script in the system's default application for it.
 */
export function OpenExternally(path: string): $CancellablePromise<void> {
    return $Call.ByID(1609395931, path);
}

/**
 * OpenScript asks for a .sql file and returns its contents. A zero value
 * means the dialog was cancelled.
 */
export function OpenScript(): $CancellablePromise<$models.OpenedFile> {
    return $Call.ByID(1099734320);
}

/**
 * ReadScript returns the current content of an open script, e.g. to pick up
 * changes made while dbird was closed.
 */
export function ReadScript(path: string): $CancellablePromise<string> {
    return $Call.ByID(573492808, path);
}

/**
 * SaveAs asks where to save content and writes it. kind selects the file
 * filter ("sql", "csv" or "tsv"). Returns "" if the dialog was cancelled.
 */
export function SaveAs(suggestedName: string, content: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(4000858594, suggestedName, content, kind);
}

/**
 * SaveScript overwrites an existing SQL script previously opened or saved.
 */
export function SaveScript(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1685239685, path, content);
}

/**
 * Watch sets the script files to watch for outside changes (the files open
 * in tabs). Changes arrive as "file:changed" events.
 */
export function Watch(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(213795786, paths);
}
