// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompletionSetup tells the editor how to autocomplete for a connection.
 */
export interface CompletionSetup {
    /**
     * Mode is "preload", "lookup" or "off" (automatic is resolved here).
     */
    "mode": string;
    "schema": string;

    /**
     * Columns holds table -> column names in preload mode.
     */
    "columns": { [_ in string]?: string[] | null } | null;
    "tableCount": number;
}

/**
 * OpenedFile is a file loaded through the open dialog.
 */
export interface OpenedFile {
    "path": string;
    "name": string;
    "content": string;
}

/**
 * UpdateStatus is what the frontend shows about self-updates.
 */
export interface UpdateStatus {
    "currentVersion": string;

    /**
     * State is one of: disabled, idle, checking, up-to-date, downloading,
     * ready, manual, error.
     */
    "state": string;

    /**
     * LatestVersion is set when a newer release was found.
     */
    "latestVersion": string;
    "notes": string;
    "releaseUrl": string;
    "error": string;
    "checkedAt": string;
}
