// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbeaver$0 from "./internal/dbeaver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbx$0 from "./internal/dbx/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as omarchy$0 from "./internal/omarchy/models.js";

/**
 * CompletionSetup tells the editor how to autocomplete for a connection.
 */
export interface CompletionSetup {
    /**
     * Mode is "preload", "lookup" or "off" (automatic is resolved here).
     */
    "mode": string;
    "schema": string;

    /**
     * Columns holds table -> column names in preload mode.
     */
    "columns": { [_ in string]?: string[] | null } | null;
    "tableCount": number;
}

/**
 * DBeaverScan is what ScanDBeaver found.
 */
export interface DBeaverScan {
    /**
     * Dir is the DBeaver workspace that was read ("" if none was found).
     */
    "dir": string;
    "candidates": dbeaver$0.Candidate[] | null;
}

/**
 * OmarchyTheme is the desktop theme dbird follows on Omarchy systems.
 */
export interface OmarchyTheme {
    "available": boolean;
    "theme": omarchy$0.Theme;
}

/**
 * OpenedFile is a file loaded through the open dialog.
 */
export interface OpenedFile {
    "path": string;
    "name": string;
    "content": string;
}

/**
 * TablePage is one page of the sidebar's table list.
 */
export interface TablePage {
    "tables": dbx$0.TableInfo[] | null;

    /**
     * Total is the number of matching tables; only set for the first page.
     */
    "total": number;
}

/**
 * UpdateStatus is what the frontend shows about self-updates.
 */
export interface UpdateStatus {
    "currentVersion": string;

    /**
     * State is one of: disabled, idle, checking, up-to-date, downloading,
     * ready, manual, error.
     */
    "state": string;

    /**
     * LatestVersion is set when a newer release was found.
     */
    "latestVersion": string;
    "notes": string;
    "releaseUrl": string;
    "error": string;
    "checkedAt": string;

    /**
     * PackageManaged is set when dbird was installed by a package manager
     * (e.g. pacman or apt) and should be updated with it.
     */
    "packageManaged": boolean;
}
