// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OpenedFile is a file loaded through the open dialog.
 */
export interface OpenedFile {
    "path": string;
    "name": string;
    "content": string;
}

/**
 * UpdateStatus is what the frontend shows about self-updates.
 */
export interface UpdateStatus {
    "currentVersion": string;

    /**
     * State is one of: disabled, idle, checking, up-to-date, downloading,
     * ready, manual, error.
     */
    "state": string;

    /**
     * LatestVersion is set when a newer release was found.
     */
    "latestVersion": string;
    "notes": string;
    "releaseUrl": string;
    "error": string;
    "checkedAt": string;
}
