// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService executes SQL from editor tabs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbx$0 from "./internal/dbx/models.js";

/**
 * Cancel aborts the running query of tabID.
 */
export function Cancel(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(554896447, tabID);
}

/**
 * CloseTab releases the dedicated connection held by tabID.
 */
export function CloseTab(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(3214469318, tabID);
}

/**
 * Run executes statements for tabID on connection connID, connecting first if
 * needed. At most maxRows rows are returned per result set.
 */
export function Run(tabID: string, connID: string, statements: string[] | null, maxRows: number, continueOnError: boolean): $CancellablePromise<dbx$0.Result[] | null> {
    return $Call.ByID(3599327438, tabID, connID, statements, maxRows, continueOnError);
}

/**
 * SaveEdits writes cells edited in the result grid back to their table, in
 * one transaction on connection connID. It returns the number of rows updated.
 */
export function SaveEdits(connID: string, req: dbx$0.EditRequest): $CancellablePromise<number> {
    return $Call.ByID(2830327577, connID, req);
}
