// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThemeService lets dbird follow the Omarchy desktop theme, live.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Omarchy returns the current Omarchy theme, if this is an Omarchy system.
 */
export function Omarchy(): $CancellablePromise<$models.OmarchyTheme> {
    return $Call.ByID(4170027995);
}
