// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService checks GitHub Releases in the background, downloads and
 * verifies new versions automatically and lets the user restart into them.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckNow runs a check immediately and returns the resulting state.
 */
export function CheckNow(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(3792226688);
}

/**
 * OpenReleasePage opens the release notes of the available version in the browser.
 */
export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByID(3134839318);
}

/**
 * Restart quits and relaunches into the downloaded version.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(3205679179);
}

/**
 * Status returns the current update state.
 */
export function Status(): $CancellablePromise<$models.UpdateStatus> {
    return $Call.ByID(1095988866);
}
