// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService persists open tabs between runs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * Load returns the saved workspace.
 */
export function Load(): $CancellablePromise<store$0.Workspace> {
    return $Call.ByID(169438308);
}

/**
 * Save stores the workspace.
 */
export function Save(w: store$0.Workspace): $CancellablePromise<void> {
    return $Call.ByID(2470231429, w);
}
