// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Theme is an Omarchy palette.
 */
export interface Theme {
    "name": string;

    /**
     * "dark" or "light"
     */
    "mode": string;
    "colors": { [_ in string]?: string } | null;
}
