// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Column describes one result column.
 */
export interface Column {
    "name": string;
    "type": string;
}

/**
 * ColumnInfo is a column of a table.
 */
export interface ColumnInfo {
    "name": string;
    "type": string;
    "nullable": boolean;
    "primaryKey": boolean;
}

/**
 * Result is the outcome of executing one statement.
 */
export interface Result {
    "sql": string;
    "columns": Column[] | null;
    "rows": ((string | null)[] | null)[] | null;
    "rowsAffected": number;

    /**
     * HasResultSet is true when the statement produced rows (even zero rows).
     */
    "hasResultSet": boolean;
    "truncated": boolean;
    "durationMs": number;
    "error": string;
}

/**
 * TableInfo is a table or view in a schema.
 */
export interface TableInfo {
    "name": string;

    /**
     * table or view
     */
    "kind": string;
}
