// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Column describes one result column.
 */
export interface Column {
    "name": string;
    "type": string;
}

/**
 * ColumnInfo is a column of a table.
 */
export interface ColumnInfo {
    "name": string;
    "type": string;
    "nullable": boolean;
    "primaryKey": boolean;
}

/**
 * EditRequest asks for rows of a table to be updated.
 */
export interface EditRequest {
    "schema": string;
    "table": string;

    /**
     * KeyColumns names the primary key columns, matching RowEdit.Key.
     */
    "keyColumns": string[] | null;
    "rows": RowEdit[] | null;
}

/**
 * Editable describes how a result set maps back to a table, so its cells can
 * be edited and saved with UPDATE statements.
 */
export interface Editable {
    "schema": string;
    "table": string;

    /**
     * Columns has, per result column, the table column it shows, or "" when
     * it shows an expression or a type dbird can't edit (binary, arrays).
     */
    "columns": string[] | null;

    /**
     * Key lists the result columns holding the table's primary key.
     */
    "key": number[] | null;
}

/**
 * Result is the outcome of executing one statement.
 */
export interface Result {
    "sql": string;
    "columns": Column[] | null;
    "rows": ((string | null)[] | null)[] | null;
    "rowsAffected": number;

    /**
     * HasResultSet is true when the statement produced rows (even zero rows).
     */
    "hasResultSet": boolean;
    "truncated": boolean;
    "durationMs": number;
    "error": string;

    /**
     * Editable is set when the rows can be edited in the grid; otherwise
     * ReadOnly says why not.
     */
    "editable": Editable | null;
    "readOnly": string;
}

/**
 * RowEdit is the change to one row: the original values of its primary key
 * (in Editable.Key order) and the new value per column (nil for NULL).
 */
export interface RowEdit {
    "key": (string | null)[] | null;
    "changes": { [_ in string]?: string | null } | null;
}

/**
 * TableInfo is a table or view in a schema.
 */
export interface TableInfo {
    "name": string;

    /**
     * table or view
     */
    "kind": string;
}
