// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Browsable describes a result that BrowseSQL can filter, sort and page.
 */
export interface Browsable {
    /**
     * Limit is the query's own LIMIT n (0 when it has none), the page size
     * for loading more rows.
     */
    "limit": number;
}

/**
 * BrowseOptions changes a simple SELECT for browsing a table: an extra filter,
 * another sort order and a page of rows.
 */
export interface BrowseOptions {
    /**
     * Filter is a condition added to the WHERE clause, e.g. "name LIKE 'A%'".
     */
    "filter": string;

    /**
     * OrderBy is the 1-based result column to sort on; 0 keeps the query's
     * own ORDER BY.
     */
    "orderBy": number;
    "desc": boolean;

    /**
     * Limit and Offset select a page; Limit 0 keeps the query's own limit.
     */
    "limit": number;
    "offset": number;
}

/**
 * Column describes one result column.
 */
export interface Column {
    "name": string;
    "type": string;
}

/**
 * ColumnInfo is a column of a table.
 */
export interface ColumnInfo {
    "name": string;
    "type": string;
    "nullable": boolean;
    "primaryKey": boolean;
}

/**
 * ColumnRef names a table column.
 */
export interface ColumnRef {
    "schema": string;
    "table": string;
    "column": string;
}

/**
 * EditColumn is what the grid needs to edit one column.
 */
export interface EditColumn {
    /**
     * Name is the table column when it can be edited, else "".
     */
    "name": string;

    /**
     * Source is the table column shown, also when it can't be edited.
     */
    "source": string;
    "type": string;

    /**
     * Kind picks the editor: text, number, bool, date, datetime, time, json
     * or enum.
     */
    "kind": string;
    "nullable": boolean;

    /**
     * HasDefault means a new row may leave the column out.
     */
    "hasDefault": boolean;
    "enum": string[] | null;

    /**
     * Ref is the column a single-column foreign key points to.
     */
    "ref": ColumnRef | null;
}

/**
 * EditRequest asks for rows of a table to be updated, inserted and deleted.
 */
export interface EditRequest {
    "schema": string;
    "table": string;

    /**
     * KeyColumns names the key columns, matching the Key of each row.
     */
    "keyColumns": string[] | null;

    /**
     * Columns lists the table columns to return for each saved row, in grid
     * order ("" for a result column that isn't a table column).
     */
    "columns": string[] | null;
    "updates": RowUpdate[] | null;
    "inserts": RowInsert[] | null;
    "deletes": RowDelete[] | null;
}

/**
 * Editable describes how a result set maps back to a table, so its cells can
 * be edited, rows added and deleted, and saved.
 */
export interface Editable {
    "schema": string;
    "table": string;

    /**
     * Columns describes each result column; Name is "" when it shows an
     * expression or a type dbird can't edit (binary, arrays, generated).
     */
    "columns": EditColumn[] | null;

    /**
     * Key lists the result columns that identify a row: the primary key, or
     * else a unique key without NULLs.
     */
    "key": number[] | null;

    /**
     * KeyName says which key that is ("primary key" or "unique key <name>").
     */
    "keyName": string;
}

/**
 * Result is the outcome of executing one statement.
 */
export interface Result {
    "sql": string;
    "columns": Column[] | null;
    "rows": ((string | null)[] | null)[] | null;
    "rowsAffected": number;

    /**
     * HasResultSet is true when the statement produced rows (even zero rows).
     */
    "hasResultSet": boolean;
    "truncated": boolean;
    "durationMs": number;
    "error": string;

    /**
     * Editable is set when the rows can be edited in the grid; otherwise
     * ReadOnly says why not.
     */
    "editable": Editable | null;
    "readOnly": string;

    /**
     * Browse is set for a SELECT from one table (or view), which can be
     * filtered, sorted and paged on the server (see BrowseSQL).
     */
    "browse": Browsable | null;
}

/**
 * RowDelete identifies a row to delete by its key as queried.
 */
export interface RowDelete {
    "key": (string | null)[] | null;
}

/**
 * RowInsert is a new row. Columns left out get their default.
 */
export interface RowInsert {
    "values": { [_ in string]?: string | null } | null;
}

/**
 * RowUpdate changes one row: the values of its key as queried (in KeyColumns
 * order), the new value per column (nil for NULL), and the values those
 * columns had when queried, to detect changes made by someone else since.
 */
export interface RowUpdate {
    "key": (string | null)[] | null;
    "changes": { [_ in string]?: string | null } | null;
    "original": { [_ in string]?: string | null } | null;
}

/**
 * SaveResult reports a save. Updated and Inserted hold the rows as stored
 * afterwards (in EditRequest.Columns order), so defaults and trigger changes
 * show up.
 */
export interface SaveResult {
    "updated": ((string | null)[] | null)[] | null;
    "inserted": ((string | null)[] | null)[] | null;
    "deleted": number;
}

/**
 * TableInfo is a table or view in a schema.
 */
export interface TableInfo {
    "name": string;

    /**
     * table or view
     */
    "kind": string;
}
