// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Connection is a saved database connection.
 */
export interface Connection {
    "id": string;
    "name": string;

    /**
     * postgres, mysql, sqlite
     */
    "driver": string;
    "host": string;
    "port": number;
    "user": string;

    /**
     * Password is never written to disk by current versions: it lives in the
     * OS password store (HasPassword). Older versions saved it here, and it
     * is moved out on startup. Towards the frontend it is only used to send
     * a newly typed password.
     */
    "password"?: string;

    /**
     * database name, or file path for sqlite
     */
    "database": string;

    /**
     * postgres only
     */
    "sslMode": string;

    /**
     * URL, when set, is used verbatim as the DSN and overrides the fields above.
     */
    "url": string;
    "color": string;

    /**
     * Completion selects how editor autocompletion gets table and column
     * names: "" (automatic), "preload", "lookup" or "off".
     */
    "completion": string;

    /**
     * HasPassword means the password is kept in the OS password store.
     */
    "hasPassword"?: boolean;

    /**
     * AskPassword means there was no password store when the password was
     * set, so dbird asks for it on connect instead of saving it.
     */
    "askPassword"?: boolean;

    /**
     * ClearPassword and CopyFrom are only sent by the frontend when saving:
     * forget the saved password, or copy the one of connection CopyFrom
     * (for duplicates). They are never stored.
     */
    "clearPassword"?: boolean;
    "copyFrom"?: string;
}

/**
 * Tab is an open SQL editor tab.
 */
export interface Tab {
    "id": string;
    "title": string;
    "connectionId": string;
    "sql": string;

    /**
     * FilePath is set when the tab is backed by a .sql file on disk.
     */
    "filePath": string;

    /**
     * Dirty is set when a file-backed tab has edits not saved to FilePath.
     */
    "dirty": boolean;
}

/**
 * Workspace is the persisted UI state.
 */
export interface Workspace {
    "tabs": Tab[] | null;
    "activeTabId": string;
}
