// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Connection is a saved database connection.
 */
export interface Connection {
    "id": string;
    "name": string;

    /**
     * postgres, mysql, sqlite
     */
    "driver": string;
    "host": string;
    "port": number;
    "user": string;
    "password": string;

    /**
     * database name, or file path for sqlite
     */
    "database": string;

    /**
     * postgres only
     */
    "sslMode": string;

    /**
     * URL, when set, is used verbatim as the DSN and overrides the fields above.
     */
    "url": string;
    "color": string;
}

/**
 * Tab is an open SQL editor tab.
 */
export interface Tab {
    "id": string;
    "title": string;
    "connectionId": string;
    "sql": string;

    /**
     * FilePath is set when the tab is backed by a .sql file on disk.
     */
    "filePath": string;
}

/**
 * Workspace is the persisted UI state.
 */
export interface Workspace {
    "tabs": Tab[] | null;
    "activeTabId": string;
}
