// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * Candidate is one DBeaver connection, converted as far as dbird supports it.
 */
export interface Candidate {
    /**
     * Key identifies the connection within the scan (project/id).
     */
    "key": string;
    "project": string;
    "folder": string;

    /**
     * Connection is the dbird connection to create. Its Name includes the
     * DBeaver folder, e.g. "Prod / billing".
     */
    "connection": store$0.Connection;

    /**
     * Problem is set when the connection can't be imported at all.
     */
    "problem": string;

    /**
     * Warnings describe settings that are dropped on import.
     */
    "warnings": string[] | null;

    /**
     * Existing names the saved dbird connection that already points at the
     * same database, if any. Scan leaves it empty.
     */
    "existing": string;
}
